language: java

env:
  matrix:
  - NODE_VERSION="12.13.1"
  global: # Get travis encrypted environment variables (Docker Password/Username)
  - secure: SpHm9ImOZdYpHggw2JcpFtlTXSJ5orBbKcz1sXvVfCpXtKCW4hlQ0Oi49PYKGH+EwXKmweSZLjQWLuUcjE7nUQs+c3vpzBtYyi/b9oOfIOyOKU/fpc+buz3W5mTkvWZxEufz0cmtKB6z1J2t9wfC2to4qF4g0V6d621mNwxaVadWz4gVAN8BRWYskBGqfAtH22pPWP2uSpMtEpT5cDQv39loTaSyqW1xcidu0N6gqY20rGI8Tu5sDH9jhV5sR9xrjA69keXnPokkS37r0uixgAlAB4X3G6oSt9DSGajmzRf8oaSgfNab0+wynvR41K0CTbQDsSI+bZEB2DxZUzVPQdsv4gwQL16MbST7dmvm1JbRO6fWg/zMiIFoE1U9FwjyeJ1PA+PJAe0jBUvQ1fFWxzdKpZJKOYHbytfOCTU5oxUcAAOJr4jA4FBzE6tTnxwRrdpANnQpIfUGqah8h4jnPOY1iCaVcsUgwhQBy1KmAERSI7Y9YKVxbVeRKafWQXb/uxdny7/2JMBlB7rKL2SlmZnrVavtkZcF5v1nOoqVSfmrcIFhuYgOKltb6vQ9LUm30s624es17i2joQwVZdwEUjK1Pft/h04KFJdnAk9k3ymUNrZKMM2wiLH9SS5hqIlr60ccFQcODEHjF7v9zNB/qY2DTjfiFuatUiPBjBm9+og=
  - secure: oycM0xy379mNxlmwRgDPUV5lUmwrV77TYBqlIV9bB+muent6gN2IkqImO6fEyyECc1Lcnrc2YkjSkGv8YeuzkZBEpfxNt+LXPHIpoZOz8K/manzxtrzBCz/Tlcsby0VHKLkJDUpYtCDq2GDyiO414mkbdMMuW5l8ydJRcsXF1P2eNEaXSyqCrdwRm8R+GWI7kPHqBzBA3e3DsvBFJKdPd1q+kBFkIYoshhdrjoAXZi2Ttp5ZDvKWmCNM5CK7+GBfnnYh9GWnP9XgEfwj0wS6r5wgYZjHplxCMAqGjRrgAlR5afwtsZCsQwJiW86BVmMtiZcUrHrqW21YJOWJRs4ty0n8uTJRwlIEkVlU9bNb0M1ggIepjn6HvBWD+45D9LeEwgo0Kl/LXI5qZl1C7xUbyqkFHgWT6OfuthgVxz3mKtCdsEKi4VwP/OPlK4YWOpchC+bTgQQmnhJZpe7UMxpmx8qVfb5zZTqEN92kgrcYnCTian+mhkA3zIFHS0AB3pNGVMOwZILlAfGCK4lBthp4tsNYeOj2sckdNCAYLMZGhoehn0R2zdalJeTn708VX12zWrEdQ8L+5CRMWBbP8qe64ooeLJgDvG0Ddy5+mVAhAnRnySF3gkA1GRM2zEGHniDiZaf1pafZSQQSu8u3SBp/TmWQZlThgZMWmQMLtrjP3PI=

services:
- docker

addons:
  ssh_know_hosts: smithlu7@129.194.69.131
  sonarcloud:
    organization: pinfo-2020
    token: # Sonarcloud login token
      secure: Hi49MH8gnqEKSPAG+r+ARp1wAp48AEMFC77d0elqVOFMtJpxdSTTDB4rTyAMHRbyGKjVedRk/MaiJ8E98VTINWKjwi+9pPCH3HOsjvwG/D9G36u3lqEsY6ynwty5gHoBX+ugF90N/zMutL0SIzVqdXVSzrrsfcK9cwSILdF0QQesU+YoOf0BcCWpAjxvaiInd9XLhNX1rAUR9zWOZ38sYSvBVVCZ9KvnKL8hh2cz1sNcdvHg+1mWBi0Z1mAPpS3FZ8wk5zLEgYTFv1Xvt+Xbn1zIX5RnlbQWjpJirdnbnXJuL+NIrfXiXD4WTt3jfd73UXA/wFx3M29C41Jg80J5+sT18GOCIvTiSk3QDhZONGa310EpH7TUXB+s6T7S6eVpaR84jgCizXwymNOAq+i/9L5KG6qc2dRr5iCxO7vklbiHnA6I2nOsrYjmwAMTByegnd8+kH4+GE0eIgPmxrvQft2wWV3EeT4i4UpxoU4jBSQsSjv++BWPWfkzUPykqb2uylnYyY3QHF19E/w/JZw5Lk9ifaom5afBDU6c7B1t7bNADlrfjMW+ny/GAzxrRFd2rUNiILyFr7nTR6D2w8bIAuEaO8KaZSIa9WTuJOru76L8xQmUi9mvM6ur7USm9bKHn3XcL03qNLI/teDFt3u1f7Wx4+Mx3+ynJE6xLUjXXfU=

cache:
    directories:
      - .autoconf
      - $HOME/.m2
      - node_modules

jobs:
  include:
  - stage: Prepare
    script:
    - nvm install $NODE_VERSION
    - mvn install -N -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - stage: Build
    script:
    - mvn install -Ppackage-docker-image
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker tag unige/api-gateway pinfo4/api-gateway:latest
    - docker tag unige/regulatory-service pinfo4/regulatory-service:latest
    - docker tag unige/valuation-service pinfo4/valuation-service:latest
    - docker tag unige/instrument-service pinfo4/instrument-service:latest
    - docker tag unige/counterparty-service pinfo4/counterparty-service:latest
    - docker push pinfo4/api-gateway:latest
    - docker push pinfo4/regulatory-service:latest
    - docker push pinfo4/valuation-service:latest
    - docker push pinfo4/instrument-service:latest
    - docker push pinfo4/counterparty-service:latest
    - mvn sonar:sonar -Dsonar.projectKey=PInfo-2020_PInfo-4 -Dsonar.organization=pinfo-2020 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=dcc92ae7dc64eccb859dcb446883d405a94733bd -Dsonar.projectName=Kernel_pinfo4
  - stage: Build
    script:
    - cd web-ui
    - pwd
    - npm -v
    - npm install
    - npm update
    - npm run-script build --prod
    - docker build -t unige/web-ui .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker tag unige/web-ui pinfo4/web-ui:latest
    - docker push pinfo4/web-ui:latest
  - stage: Deploy
    script:
    # Unencrypt ssh-key for VM
    - cd $TRAVIS_BUILD_DIR
    - pwd
    - ls
    - openssl aes-256-cbc -K $encrypted_ba497ca00145_key -iv $encrypted_ba497ca00145_iv -in pinfo4_deploy_rsa.enc -out /tmp/pinfo4_deploy_rsa -d
    - eval "$(ssh-agent -s)" # 'eval' to load the ssh-agent variables into the current environment upon starting of the ssh-agent, which we will use for logging in to the VM
    - chmod 600 /tmp/pinfo4_deploy_rsa
    - ssh-add /tmp/pinfo4_deploy_rsa
    # Clean docker compose
    - ssh smithlu7@129.194.69.131 'bash ' < clean_script.sh
    # - ssh smithlu7@129.194.69.131 'bash ~/Kernel/clean_docker_compose.sh' # Remove the current docker compose TODO: Not working, requires sudo
    # Copy docker-compose to VM
    - scp -r docker-compose smithlu7@129.194.69.131:~/Kernel/
    # Deploy script
    - ssh smithlu7@129.194.69.131 'bash ' < deploy_script.sh
    #
